---
title: "Tesla Locations"
author: "Hernan Soulages"
date: "December 19, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
iconURL <- function(type) { 
        if ("supercharger" %in% type)
                return('https://www.tesla.com/sites/all/modules/custom/tesla_findus_map/assets/icon-supercharger.png?20150604') 
        if ("standard charger" %in% type || "destination charger" %in% type)
                return('https://www.tesla.com/sites/all/modules/custom/tesla_findus_map/assets/icon-charger.png?20150604')
        if ("service" %in% type)
                return('https://www.tesla.com/sites/all/modules/custom/tesla_findus_map/assets/icon-service.png?20150604')
        return('https://www.tesla.com/sites/all/modules/custom/tesla_findus_map/assets/icon-store.png?20150604')
}

```

We used as data source a JSON from the [Tesla finder](https://www.tesla.com/findus#/bounds/49.38,-66.94,25.82,-124.39?search=supercharger,store,service,destination%20charger,&name=us) to create a Leaflet map with all the Tesla locations (stores, superchargers, chargers, service centers and stores).

```{r locations, echo=FALSE, warning=FALSE}
#locations <- read.csv('locations.txt')
fileName <- 'tesla-finder.html'
#download.file('https://www.tesla.com/findus#/bounds/49.38,-66.94,25.82,-124.39?search=supercharger,store,service,destination%20charger,&name=us', fileName)
fileString <- readChar(fileName, file.info(fileName)$size)
library(stringr)
jsonStr <- str_match(fileString, 'var location_data =\\s*(\\[\\{.+\\}\\]);\\s+var production = true;')[2]
library(jsonlite)
df <- fromJSON(jsonStr)
library(plyr)
df <- transform(df, latitude = as.numeric(latitude), longitude = as.numeric(longitude))
df <- rename(df, c("latitude"="lat", "longitude"="lng"))
df$iconAddress <- sapply(df$location_type, iconURL)
library(leaflet)
df %>% leaflet(1024, 768) %>% addTiles() %>% 
        addMarkers(~lng, ~lat, clusterOptions = markerClusterOptions(maxClusterRadius=30, disableClusteringAtZoom=10), icon = ~ icons( iconUrl = iconAddress, iconWidth = 32, iconHeight = 32), popup = paste("<b>", df$title, "</b><br/><emp>", df$address, "</emp><br/>", df$location_type))
```